version: '3.8'

services:
  ollama_gpu:
    image: ollama/ollama:0.0.0-rocm
    container_name: ollama_gpu_3
    environment:
      - HIP_PATH=/opt/rocm/lib/
      - LD_LIBRARY_PATH=/opt/rocm/lib
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama:
